name: mindingherdia
description: "MindingHerDia"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  stylish_bottom_bar: ^1.1.0
  flutter_screenutil: ^5.5.3
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^3.1.0
  google_maps_flutter: ^2.1.5
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  flutter_spinkit: ^5.2.1
  modal_bottom_sheet: ^3.0.0
  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^25.1.39
  vs_scrollbar: ^1.0.0
  custom_map_markers: ^0.0.2+1
  image_picker: ^1.0.7
  graphql_flutter:
  shared_preferences: ^2.2.3
  slide_action: ^0.0.2
  chewie: ^1.8.1
  video_player: ^2.8.6
  subtitle_wrapper_package: ^2.2.1
  firebase_core:
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_core_platform_interface: ^5.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/Svgs/
    - assets/Images/
    - assets/Images/reversal/
    - assets/Learn/50_fun_facts/
    - assets/Learn/enery_diet/
    - assets/Learn/feast_on_health/
    - assets/Learn/food_reciepe/
    - assets/Learn/healthy_gut/
    - assets/Learn/medication/
    - assets/Learn/mental_health/
    - assets/Learn/nutrition/
    - assets/Learn/weekly_meal/
